// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrzmfhwzoeutokzyypwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyem1maHd6b2V1dG9renl5cHd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyMjI3OTQsImV4cCI6MjA4MDc5ODc5NH0.L78vTTlLx4mqcx4qzc3wbfUUprrWb9BFkX2yUbAJ5Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});